name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
        name: Install dependencies

      - run: pnpm run test:unit
        name: Run Unit Tests